### ISSUE TITLE
Problema de código en el archivo 4.-

### ISSUE THREAD

**Issue by l1b3** [Programa-Resuelto/CursoPythonProgramaResuelto#1]
Hola!
Comienzo por darte las gracias en haber realizado estos ejercicios para iniciarnos en Python!
La verdad soy nuevo en la programación y ahora me he quedado estancado en el ejercicio "4 Variables como número - Ejercicio.py"

**Escribí el código pero tengo el siguiente problemas al ejecutar el código en Python.**(ejecuto el fichero en la terminal de Ubuntu, tengo Python 3.7.5 instalado)

libe@libe-HP-Notebook:~/Documentos/PHYTON/EJERCICIOS/CursoPythonProgramaResuelto-master$ python3 '4 Variables como números - Ejercicio.py'
Traceback (most recent call last):
  File "4 Variables como números - Ejercicio.py", line 29, in <module>
    print("No puedes comprar tequila.")
TypeError: 'tuple' object is not callable

La verdad me tomé el tiempo de volver a leer guías para autocorregirme, sin embargo luego de un par de horas decidí preguntarte directamente cuál es el error que estoy cometiendo porque no he podido salir de él. Quiero corregirlo para luego moverme al siguiente ejercicio.

Te muestro el código a continuación:

#Estás con tus amigos y quieren comprar entre todos una botella de Tequila.
#La botella de Tequila tiene un precio de 65 dólares.
#En la línea 4, crea una variable llamada dineroTotal y asígnale el número 0.
dineroTotal = int(0)
#Tú tienes 14.50 dólares.
#En la línea 7, crea una variable llamada miDinero con el dinero que tienes.
miDinero = float(14.50)
#Tu amigo Luis tiene 17 dólares.
#En la línea 10, crea una variable llamada dineroLuis con el dinero que él tiene.
dineroLuis = int(10)
#Tu amiga Valentina tiene 12.15 dólares.
#En la línea 13, crea una variable llamada dineroValentina con el dinero que ella tiene.
dineroValentina = float(12.15)
#Tu amigo Daniel tiene 20 dólares.
#En la línea 16, crea una variable llamada dineroDaniel con el dinero que él tiene.
dineroDaniel = int(20)
#Ahora, en la línea 20, vamos a contar el dinero que tienen entre todos.
#Actualiza la variable dineroTotal para que sea igual a la suma del dinero de todos.
#No uses los números directamente en la suma, sino las variables.
dineroTotal = (float(miDinero+dineroLuis+dineroValentina+dineroDaniel))
#En la línea 22, imprime la variable dineroTotal para saber cuánto dinero tienen.
print = dineroTotal
#¿Tienen suficiente dinero para comprar la botella de Tequila?
#En la línea 25 imprime un mensaje para decirle a tus amigos si pueden comprar la botella o no.
print =()
if dineroTotal >=float(65.0):
	print("Puedes comprar tequila.")
else:
	print("No puedes comprar tequila.")

Gracias por tu tiempo.

Saludos.

Libe.

**Comment by Programa-Resuelto** [comment]
> Hola!
> Comienzo por darte las gracias en haber realizado estos ejercicios para iniciarnos en Python!
> La verdad soy nuevo en la programación y ahora me he quedado estancado en el ejercicio "4 Variables como número - Ejercicio.py"
> 
> **Escribí el código pero tengo el siguiente problemas al ejecutar el código en Python.**(ejecuto el fichero en la terminal de Ubuntu, tengo Python 3.7.5 instalado)
> 
> libe@libe-HP-Notebook:~/Documentos/PHYTON/EJERCICIOS/CursoPythonProgramaResuelto-master$ python3 '4 Variables como números - Ejercicio.py'
> Traceback (most recent call last):
> File "4 Variables como números - Ejercicio.py", line 29, in
> print("No puedes comprar tequila.")
> TypeError: 'tuple' object is not callable
> 
> La verdad me tomé el tiempo de volver a leer guías para autocorregirme, sin embargo luego de un par de horas decidí preguntarte directamente cuál es el error que estoy cometiendo porque no he podido salir de él. Quiero corregirlo para luego moverme al siguiente ejercicio.
> 
> Te muestro el código a continuación:
> 
> #Estás con tus amigos y quieren comprar entre todos una botella de Tequila.
> #La botella de Tequila tiene un precio de 65 dólares.
> #En la línea 4, crea una variable llamada dineroTotal y asígnale el número 0.
> dineroTotal = int(0)
> #Tú tienes 14.50 dólares.
> #En la línea 7, crea una variable llamada miDinero con el dinero que tienes.
> miDinero = float(14.50)
> #Tu amigo Luis tiene 17 dólares.
> #En la línea 10, crea una variable llamada dineroLuis con el dinero que él tiene.
> dineroLuis = int(10)
> #Tu amiga Valentina tiene 12.15 dólares.
> #En la línea 13, crea una variable llamada dineroValentina con el dinero que ella tiene.
> dineroValentina = float(12.15)
> #Tu amigo Daniel tiene 20 dólares.
> #En la línea 16, crea una variable llamada dineroDaniel con el dinero que él tiene.
> dineroDaniel = int(20)
> #Ahora, en la línea 20, vamos a contar el dinero que tienen entre todos.
> #Actualiza la variable dineroTotal para que sea igual a la suma del dinero de todos.
> #No uses los números directamente en la suma, sino las variables.
> dineroTotal = (float(miDinero+dineroLuis+dineroValentina+dineroDaniel))
> #En la línea 22, imprime la variable dineroTotal para saber cuánto dinero tienen.
> print = dineroTotal
> #¿Tienen suficiente dinero para comprar la botella de Tequila?
> #En la línea 25 imprime un mensaje para decirle a tus amigos si pueden comprar la botella o no.
> print =()
> if dineroTotal >=float(65.0):
> print("Puedes comprar tequila.")
> else:
> print("No puedes comprar tequila.")
> 
> Gracias por tu tiempo.
> 
> Saludos.
> 
> Libe.

Hola! Me alegra tu interés por seguir mi curso! Gracias!

En Python no necesitas especificar el tipo de dato cuando creas la variable. En vez de "dineroLuis = int(10)" puedes escribir directamente "dineroLuis = 10" y en vez de "dineroValentina = float(12.15)" puedes escribir directamente "dineroValentina = 12.15". Igual en la suma de la línea 20, puedes sumar directamente. En la condicional también puedes quitar el "float" del número 65.

Aun así, esto no es lo que genera el error en tu programa, sino otras dos cosas. Mira las líneas 22 y 25:

"print = dineroTotal
print =()"

Estás usando print =, pero print es una función, no una variable. No la tienes que igualar a nada. La Corrección sería:

"print (dineroTotal)
print ()"

No olvides que tienes que colocar indentación o tabulación en las condiciones también. 

Ya con esto debe funcionar. Saludos!

**Comment by l1b3** [comment]
Oh! No lo noté para nada ^^'.
Gracias por los comentarios de las variables y los de las líneas 22 y 25.

Ya terminé los ejercicios. Seguiré leyendo y jugando más!
Saludos ;)

**Comment by goal2021** [comment]
hola como estas estoy empezando a estudiar python y hacer  estos ejercicos pero m salen error gracias por ofrecer estos ejercicios para poder practicar muy agradecida por tomar tu tiempo para esto ..
# Estás con tus amigos y quieren comprar entre todos una botella de Tequila.
# La botella de Tequila tiene un precio de 65 dólares.
# En la línea 4, crea una variable llamada dineroTotal y asígnale el número 0.
dineroTotal=0
# Tú tienes 14.50 dólares.
# En la línea 7, crea una variable llamada miDinero con el dinero que tienes.
miDinero=14.50
# Tu amigo Luis tiene 17 dólares.
# En la línea 10, crea una variable llamada dineroLuis con el dinero que él tiene.
dineroLuis=17
# Tu amiga Valentina tiene 12.15 dólares.
# En la línea 13, crea una variable llamada dineroValentina con el dinero que ella tiene.
dineroValentina=12.15
# Tu amigo Daniel tiene 20 dólares.
# En la línea 16, crea una variable llamada dineroDaniel con el dinero que él tiene.
dineroDaniel=20
# Ahora, en la línea 20, vamos a contar el dinero que tienen entre todos.
# Actualiza la variable dineroTotal para que sea igual a la suma del dinero de todos.
# No uses los números directamente en la suma, sino las variables.
dineroTotal=(float(miDinero+dineroluis+dineroValentina+dineroDaniel))
# En la línea 22, imprime la variable dineroTotal para saber cuánto dinero tienen.
print(dineroTotal)
# ¿Tienen suficiente dinero para comprar la botella de Tequila?
# En la línea 25 imprime un mensaje para decirle a tus amigos si pueden comprar la botella o no.
print('no pueden comprar tequila')
no ae que pasa el linie de dinero total pongo las variables y me sale dinero luis no esta identificado y me sale que es incorrecto
